package main

import (
	"slices"
	"strings"
	"unicode"
	"unicode/utf8"
)

// Definition matching is the reverse of the gloss stage: instead of replacing a
// word with a word from its definition, it replaces a phrase that reads like a
// definition with the headword being defined ("a person who writes
// professionally" -> "author"). It is the one stage that collapses N words to
// one, and the one most able to change meaning, so it is opt-in.
//
// The index is generated by tools/gendefs.py from WordNet's dominant-sense
// glosses: defWords holds headwords most-common-first, defSigs their gloss
// keywords, defIndex the keyword -> headword postings.

const (
	defMinWindow = 2 // shortest phrase considered
	defMaxWindow = 6 // longest; beyond this a phrase is rarely one definition
	// defMaxExtra caps how many content words in the window the signature does
	// not account for. Without it a long window matches on a two-keyword
	// signature and the surplus is simply deleted: "female offspring landowner"
	// would collapse to "daughter", losing the landowner.
	defMaxExtra = 1
)

// defCarrierWords are the nouns a definition-like phrase hangs its keywords on
// ("a person who writes professionally"). They are the only words allowed to
// fill the defMaxExtra slot; any other surplus word carries meaning of its own
// and must not be swallowed by a replacement.
var defCarrierWords = map[string]bool{
	"act": true, "action": true, "condition": true, "device": true,
	"instrument": true, "kind": true, "manner": true, "man": true,
	"one": true, "people": true, "person": true, "place": true,
	"process": true, "quality": true, "someone": true, "something": true,
	"sort": true, "state": true, "thing": true, "type": true,
	"way": true, "woman": true,
}

// defToken is one alphabetic word and where it sits in the source text.
type defToken struct {
	lower      string
	start, end int
}

// defTokenize splits text into alphabetic words, using the same character rule
// as swapWords so both stages agree on what a word is.
func defTokenize(text string) []defToken {
	var out []defToken
	start := -1
	for i, r := range text {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') {
			if start < 0 {
				start = i
			}
			continue
		}
		if start >= 0 {
			out = append(out, defToken{strings.ToLower(text[start:i]), start, i})
			start = -1
		}
	}
	if start >= 0 {
		out = append(out, defToken{strings.ToLower(text[start:]), start, len(text)})
	}
	return out
}

// applyDefMatch replaces definition-like phrases with the headword they define.
// Windows are tried longest-first and consumed greedily: a replaced span is
// never reconsidered, so neighbouring phrases each get at most one match.
func applyDefMatch(text string) string { return applyDefMatchInto(text, nil) }

// applyDefMatchInto is applyDefMatch with a record of what it produced. Every
// headword it writes is added to produced (lowercased) so later stages can
// leave it alone — a gloss swap on a fresh headword undoes the match and can
// invert its sense (anarchy -> law).
func applyDefMatchInto(text string, produced map[string]bool) string {
	if len(defWords) == 0 {
		return text
	}
	toks := defTokenize(text)
	if len(toks) < defMinWindow {
		return text
	}

	var b strings.Builder
	pos := 0
	for i := 0; i < len(toks); {
		n := defMaxWindow
		if rest := len(toks) - i; n > rest {
			n = rest
		}
		matched := false
		for ; n >= defMinWindow; n-- {
			span := text[toks[i].start:toks[i+n-1].end]
			// A protected literal sits in the text as \x00N\x00; absorbing one
			// into a match would delete it, so skip any window holding one.
			if strings.ContainsRune(span, 0) {
				continue
			}
			word, ok := defMatchWindow(toks[i:i+n], span)
			if !ok {
				continue
			}
			b.WriteString(text[pos:toks[i].start])
			b.WriteString(word)
			if produced != nil {
				produced[strings.ToLower(word)] = true
			}
			pos = toks[i+n-1].end
			i += n
			matched = true
			break
		}
		if !matched {
			i++
		}
	}
	b.WriteString(text[pos:])
	return b.String()
}

// defMatchWindow returns the headword defined by this window, if any.
//
// Three gates decide it: every keyword of the candidate's signature must appear
// in the window (a partial match is what produces nonsense), the window may
// carry at most defMaxExtra content words the signature does not account for
// (otherwise the surplus is silently dropped), and the headword must cost
// strictly fewer tokens than the span it would replace.
func defMatchWindow(toks []defToken, span string) (string, bool) {
	content := make(map[string]bool, len(toks))
	for _, t := range toks {
		if !defStopWords[t.lower] {
			content[t.lower] = true
		}
	}
	if len(content) < defMinWindow {
		return "", false
	}

	hits := make(map[uint32]int, len(content)*4)
	for w := range content {
		for _, id := range defIndex[w] {
			hits[id]++
		}
	}

	spanTokens := estimateTokens(span)
	var (
		best     string
		bestSig  int
		bestTok  int
		bestID   uint32
		haveBest bool
	)
	for id, n := range hits {
		if int(id) >= len(defSigs) || n != len(defSigs[id]) {
			continue // partial signature match
		}
		if !defSurplusIsCarried(content, defSigs[id]) {
			continue // window says more than the definition does
		}
		word := defWords[id]
		tok := estimateTokens(word)
		if tok >= spanTokens {
			continue // not actually cheaper
		}
		// Most specific signature wins; ties go to the cheaper word, then to
		// the lower id, which the generator assigns in frequency order.
		if !haveBest || n > bestSig ||
			(n == bestSig && (tok < bestTok || (tok == bestTok && id < bestID))) {
			best, bestSig, bestTok, bestID, haveBest = word, n, tok, id, true
		}
	}
	if !haveBest {
		return "", false
	}
	return matchCase(span, best), true
}

// defSurplusIsCarried reports whether the window's content words beyond the
// signature are few enough, and bland enough, to drop with the replacement.
func defSurplusIsCarried(content map[string]bool, sig []string) bool {
	extra := 0
	for w := range content {
		if slices.Contains(sig, w) {
			continue
		}
		if !defCarrierWords[w] {
			return false
		}
		if extra++; extra > defMaxExtra {
			return false
		}
	}
	return true
}

// matchCase capitalizes the replacement when the phrase it replaces started
// with a capital, so sentence openings survive the swap.
func matchCase(span, word string) string {
	r, _ := utf8.DecodeRuneInString(span)
	if !unicode.IsUpper(r) {
		return word
	}
	w, size := utf8.DecodeRuneInString(word)
	if w == utf8.RuneError {
		return word
	}
	return string(unicode.ToUpper(w)) + word[size:]
}
