#!/usr/bin/env python3
# Generates gloss_data.go: word -> shortest defining word from its own
# dictionary definition. Experimental, lossy source for turo's -gloss stage.
#
# For each headword in dictionary.csv it scans the definition text for the
# fewest-token word that is itself a dictionary headword, shares the headword's
# coarse part of speech, is at least 3 letters, and costs strictly fewer tokens.
# Prose definitions are noisy, so the POS gate removes the worst picks
# ("utilize" -> "one"); the reducer's runtime sameClass gate is a second guard.
#
# Requires: pip install tiktoken
# Run:      python3 tools/gengloss.py

import csv
import re
import sys

try:
    import tiktoken
except ImportError:
    sys.exit("need tiktoken: pip install tiktoken")

enc = tiktoken.get_encoding("cl100k_base")
tok = lambda s: len(enc.encode(s))
alpha = re.compile(r"[a-z]+")


def coarse(wordtype):
    wt = wordtype.strip()
    if wt.startswith(("v.", "p. p.", "imp.", "p. pr.")):
        return "v"
    if wt in ("a.", "superl."):
        return "a"
    if wt in ("adv.", "adv", "prep.", "conj."):
        return "r"
    if wt == "n." or wt.startswith("n. pl"):
        return "n"
    return None


def main():
    pos = {}   # word -> coarse POS
    defn = {}  # word -> definition text
    with open("dictionary.csv", encoding="utf-8", errors="ignore") as f:
        for row in csv.reader(f):
            if len(row) < 3:
                continue
            w = row[0].strip().lower()
            if not w or not w.isalpha() or w in pos:
                continue
            c = coarse(row[1])
            if c:
                pos[w] = c
                defn[w] = row[2].lower()

    pairs = {}
    for w, dtext in defn.items():
        tw = tok(w)
        if tw < 2:
            continue
        best = None  # (tokens, len, word)
        for cand in alpha.findall(dtext):
            if cand == w or len(cand) < 3 or pos.get(cand) != pos[w]:
                continue
            tc = tok(cand)
            if tc < tw:
                key = (tc, len(cand), cand)
                if best is None or key < best:
                    best = key
        if best:
            pairs[w] = best[2]

    with open("gloss_data.go", "w") as out:
        out.write("// Code generated by tools/gengloss.py; DO NOT EDIT.\n")
        out.write("// Shortest same-POS defining word from each dictionary\n")
        out.write("// definition, measured with the cl100k_base tokenizer.\n\n")
        out.write("package main\n\n")
        out.write("// definitionGloss maps a word to the shortest defining word\n")
        out.write("// found in its dictionary definition (fewer tokens, same POS).\n")
        out.write("var definitionGloss = map[string]string{\n")
        for w in sorted(pairs):
            out.write('\t"%s": "%s",\n' % (w, pairs[w]))
        out.write("}\n")
    print("wrote gloss_data.go with %d entries" % len(pairs))


if __name__ == "__main__":
    main()
