#!/usr/bin/env python3
# Generates thesaurus_data.go from thesaurus.txt (Moby format) using a real
# tokenizer. For each word it picks the reciprocal synonym with the fewest
# tokens (tie: shortest, then alphabetical). Only strict token reductions are
# kept. Requires: pip install tiktoken. Run: python3 tools/gensyn.py
import re, sys
try:
    import tiktoken
except ImportError:
    sys.exit("need tiktoken: pip install tiktoken")
enc = tiktoken.get_encoding("cl100k_base")
tok = lambda s: len(enc.encode(s))
alpha = re.compile(r'^[a-z]+$')

syn = {}
with open("thesaurus.txt", encoding="utf-8", errors="ignore") as f:
    for line in f:
        parts = [p.strip().lower() for p in line.rstrip("\n").split(",")]
        if not parts or not alpha.match(parts[0]):
            continue
        syn[parts[0]] = [p for p in parts[1:] if alpha.match(p)]

pairs = {}
for w, ss in syn.items():
    if len(w) < 4:
        continue
    tw = tok(w)
    if tw < 2:
        continue
    best = None
    for s in set(ss):
        if s == w or len(s) < 2 or s not in syn or w not in syn[s]:
            continue
        ts = tok(s)
        if ts < tw:
            key = (ts, len(s), s)
            if best is None or key < best[0]:
                best = (key, s)
    if best:
        pairs[w] = best[1]

with open("thesaurus_data.go", "w") as out:
    out.write("// Code generated by tools/gensyn.py; DO NOT EDIT.\n")
    out.write("// Reciprocal fewest-token synonyms from the Moby thesaurus,\n")
    out.write("// measured with the cl100k_base tokenizer.\n\n")
    out.write("package main\n\n")
    out.write("// shorterSynonym maps a word to a synonym that costs fewer tokens.\n")
    out.write("var shorterSynonym = map[string]string{\n")
    for w in sorted(pairs):
        out.write('\t"%s": "%s",\n' % (w, pairs[w]))
    out.write("}\n")
print("wrote thesaurus_data.go with %d entries" % len(pairs))
