#!/usr/bin/env python3
# Generates thesaurus_data.go: a word -> token-cheaper-synonym map.
#
# Source is WordNet (tight synsets), not the Moby association list, and every
# candidate is frequency-filtered so swaps land on common words instead of
# archaic ones ("utilize" -> "use", not "ply"). A swap is emitted only when the
# synonym:
#   - shares the word's part of speech (same WordNet POS),
#   - is a single alphabetic word,
#   - is common enough (Zipf frequency >= MIN_SYN_ZIPF) and not much rarer than
#     the word itself,
#   - costs strictly fewer tokens (cl100k) than the word.
# Among valid candidates the fewest-token, then most-frequent, then shortest
# synonym wins.
#
# Requires: pip install nltk wordfreq tiktoken
#           python -c "import nltk; nltk.download('wordnet'); nltk.download('omw-1.4')"
# Run:      python3 tools/gensyn.py

import re
import sys

try:
    import tiktoken
    from nltk.corpus import wordnet as wn
    from wordfreq import zipf_frequency
except ImportError as e:
    sys.exit(f"missing dependency: {e}\n"
             "install: pip install nltk wordfreq tiktoken\n"
             "then:    python -c \"import nltk; nltk.download('wordnet'); nltk.download('omw-1.4')\"")

enc = tiktoken.get_encoding("cl100k_base")
tok = lambda s: len(enc.encode(s))
alpha = re.compile(r"^[a-z]+$")

MIN_WORD_ZIPF = 1.5   # skip words nobody uses (keeps the map relevant + small)
MIN_SYN_ZIPF = 3.0    # synonym must be a common word (kills archaic swaps)
MAX_ZIPF_DROP = 1.0   # synonym may be at most this much rarer than the word

# WordNet POS -> our label; only same-POS swaps are allowed.
POS = {wn.NOUN: "n", wn.VERB: "v", wn.ADJ: "a", wn.ADV: "r"}


def synonyms_by_pos(word):
    """Map POS -> set of same-POS single-word synonyms of `word`."""
    out = {}
    for syn in wn.synsets(word):
        p = POS.get(syn.pos())
        if p is None:
            continue
        for lemma in syn.lemmas():
            name = lemma.name().lower()
            if name != word and alpha.match(name):
                out.setdefault(p, set()).add(name)
    return out


def best_synonym(word):
    zw = zipf_frequency(word, "en")
    if zw < MIN_WORD_ZIPF:
        return None
    tw = tok(word)
    if tw < 2:
        return None
    best = None  # (tokens, -zipf, len, name)
    for _pos, names in synonyms_by_pos(word).items():
        for s in names:
            zs = zipf_frequency(s, "en")
            if zs < MIN_SYN_ZIPF or zs < zw - MAX_ZIPF_DROP:
                continue
            ts = tok(s)
            if ts >= tw:
                continue
            key = (ts, -zs, len(s), s)
            if best is None or key < best[0]:
                best = (key, s)
    return best[1] if best else None


def main():
    pairs = {}
    seen = set()
    for syn in wn.all_synsets():
        for lemma in syn.lemmas():
            w = lemma.name().lower()
            if w in seen or not alpha.match(w) or len(w) < 4:
                continue
            seen.add(w)
            s = best_synonym(w)
            if s:
                pairs[w] = s

    with open("thesaurus_data.go", "w") as out:
        out.write("// Code generated by tools/gensyn.py; DO NOT EDIT.\n")
        out.write("// Token-cheaper synonyms from WordNet, frequency-filtered\n")
        out.write("// (wordfreq) and measured with the cl100k_base tokenizer.\n\n")
        out.write("package main\n\n")
        out.write("// shorterSynonym maps a word to a common, same-part-of-speech\n")
        out.write("// synonym that costs fewer tokens.\n")
        out.write("var shorterSynonym = map[string]string{\n")
        for w in sorted(pairs):
            out.write('\t"%s": "%s",\n' % (w, pairs[w]))
        out.write("}\n")
    print("wrote thesaurus_data.go with %d entries" % len(pairs))


if __name__ == "__main__":
    main()
